"""Self-contained dashboard for the hackathon demo."""

DASHBOARD_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Opportunity Memory Agent</title><style>
:root{color-scheme:dark;--bg:#07111f;--card:#102238;--line:#28435f;--accent:#55d6be;--muted:#9eb3c8}*{box-sizing:border-box}body{margin:0;background:linear-gradient(135deg,#07111f,#102b3c);color:#f4f8fb;font:16px system-ui,sans-serif}main{width:min(1120px,94vw);margin:32px auto 60px}header{display:flex;justify-content:space-between;gap:20px;align-items:end}h1{margin:0;font-size:clamp(30px,5vw,54px)}h2{margin:0 0 14px}p{color:var(--muted)}.badge{color:#07111f;background:var(--accent);padding:7px 11px;border-radius:99px;font-weight:700}.grid{display:grid;grid-template-columns:1fr 1.5fr;gap:18px;margin-top:24px}.card{background:#102238e8;border:1px solid var(--line);border-radius:18px;padding:20px;box-shadow:0 18px 50px #0004}label{display:block;color:var(--muted);margin-top:11px;font-size:13px}input,select,textarea,button{width:100%;border:1px solid var(--line);border-radius:10px;padding:11px;margin-top:5px;background:#071625;color:white}button{border:0;background:var(--accent);color:#07111f;font-weight:800;cursor:pointer;margin-top:15px}button.secondary{background:#29445e;color:white}.action{padding:14px 0;border-top:1px solid var(--line)}.action:first-child{border-top:0}.score{float:right;color:var(--accent);font-weight:800}.meta{color:var(--muted);font-size:13px}pre{white-space:pre-wrap;color:#d9f7f1;background:#081827;padding:14px;border-radius:10px;min-height:90px}#notice{min-height:22px;color:var(--accent)}@media(max-width:760px){.grid{grid-template-columns:1fr}header{align-items:start;flex-direction:column}}
</style></head><body><main>
<header><div><h1>Opportunity Memory Agent</h1><p>Durable decisions. Grounded actions. No lost context.</p></div><span class="badge">CockroachDB + Gemini</span></header>
<div class="grid"><section class="card"><h2>Add opportunity</h2><form id="create-form">
<label>Name<input name="name" required minlength="2"></label><label>Reward (USD)<input name="reward_usd" type="number" min="0" value="1000" required></label><label>Deadline<input name="deadline" type="datetime-local"></label><label>Confidence<input name="confidence" type="number" min="0" max="1" step="0.05" value="0.5" required></label><label>Next action<textarea name="next_action" required>Review eligibility and prepare submission</textarea></label><button>Create and remember</button></form><div id="notice"></div></section>
<section class="card"><h2>Ranked action queue</h2><div id="actions">Loading…</div><button class="secondary" id="refresh">Refresh queue</button></section>
<section class="card"><h2>Append memory</h2><form id="event-form"><label>Opportunity<select id="opportunity-id" required></select></label><label>Event<select name="kind"><option>progress</option><option>review</option><option>blocker</option><option>submission</option></select></label><label>Detail<textarea name="detail" required>Prepared reproducible demo evidence</textarea></label><label>Status<select name="status"><option value="">No change</option><option>active</option><option>blocked</option><option>submitted</option><option>closed</option></select></label><button>Append immutable event</button></form><button class="secondary" id="show-memory">Show timeline</button><pre id="memory">Select an opportunity to inspect its timeline.</pre></section>
<section class="card"><h2>Grounded Gemini brief</h2><p>Gemini sees only the bounded facts in the ranked queue.</p><button id="brief-button">Generate brief</button><pre id="brief">No brief generated yet.</pre></section></div>
</main><script>
const actionsNode=document.querySelector('#actions'),select=document.querySelector('#opportunity-id'),notice=document.querySelector('#notice');async function json(url,options={}){const response=await fetch(url,options),body=await response.json();if(!response.ok)throw new Error(body.detail||response.statusText);return body}function escapeHtml(value){const node=document.createElement('span');node.textContent=value;return node.innerHTML}async function loadActions(){const actions=await json('/actions');actionsNode.innerHTML='';select.innerHTML='';if(!actions.length)actionsNode.textContent='No active opportunities yet.';for(const item of actions){const o=item.opportunity;actionsNode.insertAdjacentHTML('beforeend',`<div class="action"><span class="score">${item.urgency_score.toFixed(1)}</span><strong>${escapeHtml(o.name)}</strong><div class="meta">$${o.reward_usd.toLocaleString()} · ${o.status} · ${o.deadline?new Date(o.deadline).toLocaleString():'no deadline'}</div><div>${escapeHtml(o.next_action)}</div><div class="meta">${escapeHtml(item.reason)}</div></div>`);select.add(new Option(o.name,o.id))}}function payload(form){const data=Object.fromEntries(new FormData(form));for(const key of Object.keys(data))if(data[key]==='')delete data[key];return data}
document.querySelector('#create-form').onsubmit=async event=>{event.preventDefault();try{const body=payload(event.target);body.reward_usd=Number(body.reward_usd);body.confidence=Number(body.confidence);if(body.deadline)body.deadline=new Date(body.deadline).toISOString();await json('/opportunities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});notice.textContent='Opportunity stored with its first memory event.';event.target.reset();await loadActions()}catch(error){notice.textContent=error.message}};document.querySelector('#event-form').onsubmit=async event=>{event.preventDefault();try{await json(`/opportunities/${select.value}/events`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload(event.target))});notice.textContent='Memory event appended.';await loadActions()}catch(error){notice.textContent=error.message}};document.querySelector('#show-memory').onclick=async()=>{try{const events=await json(`/opportunities/${select.value}/memory`);document.querySelector('#memory').textContent=events.map(e=>`${new Date(e.created_at).toLocaleString()} · ${e.kind}\n${e.detail}`).join('\n\n')||'No events.'}catch(error){notice.textContent=error.message}};document.querySelector('#brief-button').onclick=async()=>{const node=document.querySelector('#brief');node.textContent='Generating…';try{node.textContent=(await json('/actions/brief')).brief}catch(error){node.textContent=error.message}};document.querySelector('#refresh').onclick=loadActions;loadActions().catch(error=>actionsNode.textContent=error.message);
</script></body></html>"""
